Informative error message when namespace property doesn't exist
TypeError: Cannot read property 'addReference' of undefined
->
Export 'foo' is not defined by '<module name>'